### ISSUE TITLE
Getting no such file or directory

### ISSUE THREAD

**Issue by jrock2004** [danlynn/ember-cli#21]
Been using your image and every once in a while after some saves, I get the following error. Thoughts on what this could be? I am using `ember-cli:2.18.2`.

```
cf2-ember | file changed templates/location/select-staff.hbs
cf2-ember | Build Error (ConfigLoader)
cf2-ember |
cf2-ember | ENOENT: no such file or directory, scandir '/myapp/tmp/config_loader-input_base_path-eWisJ1Zu.tmp/'
cf2-ember |
cf2-ember |
cf2-ember | Stack Trace and Error Report: /tmp/error.dump.64132dcb682679c99cc5cb5057b1ea7f.log
```

Here is the log file

```
ERROR Summary:

  - broccoliBuilderErrorStack: Error: ENOENT: no such file or directory, scandir '/myapp/tmp/config_loader-input_base_path-eWisJ1Zu.tmp/'
    at Object.fs.readdirSync (fs.js:904:18)
    at _walkSync (/myapp/node_modules/walk-sync/index.js:74:18)
    at Function.entries (/myapp/node_modules/walk-sync/index.js:50:10)
    at ConfigLoader.CachingWriter._conditionalBuild (/myapp/node_modules/broccoli-caching-writer/index.js:112:24)
    at /myapp/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/myapp/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/myapp/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/myapp/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/myapp/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

  - codeFrame: ENOENT: no such file or directory, scandir '/myapp/tmp/config_loader-input_base_path-eWisJ1Zu.tmp/'
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `ConfigLoader` plugin. 💥
ENOENT: no such file or directory, scandir '/myapp/tmp/config_loader-input_base_path-eWisJ1Zu.tmp/'
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Build Canceled: Broccoli Builder ran into an error with `ConfigLoader` plugin. 💥
ENOENT: no such file or directory, scandir '/myapp/tmp/config_loader-input_base_path-eWisJ1Zu.tmp/'
  - name: Error
  - nodeAnnotation: ConfigLoader
  - nodeName: ConfigLoader
  - originalErrorMessage: ENOENT: no such file or directory, scandir '/myapp/tmp/config_loader-input_base_path-eWisJ1Zu.tmp/'
  - stack: Error: ENOENT: no such file or directory, scandir '/myapp/tmp/config_loader-input_base_path-eWisJ1Zu.tmp/'
    at Object.fs.readdirSync (fs.js:904:18)
    at _walkSync (/myapp/node_modules/walk-sync/index.js:74:18)
    at Function.entries (/myapp/node_modules/walk-sync/index.js:50:10)
    at ConfigLoader.CachingWriter._conditionalBuild (/myapp/node_modules/broccoli-caching-writer/index.js:112:24)
    at /myapp/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/myapp/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/myapp/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/myapp/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/myapp/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by jrock2004** [comment]
I am wondering if this could be related to watchman. When I was using my own image, it did not have watchman installed
